version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  zaakbrug:
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-7.9-20231026.224138}
    image: wearefrank/zaakbrug:${ZAAKBRUG_VERSION:-latest}
    container_name: zaakbrug.dev
    environment:
      - zaakbrug.zds.timezone=UTC
      - TZ=Europe/Amsterdam
    volumes:
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      # - ./data:/usr/local/tomcat/data
      - ./src/main/configurations:/opt/frank/configurations:ro
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080

  soapui-testrunner:
    profiles:
      - soapui
    image: smartbear/soapuios-testrunner:latest
    volumes:
      - ./e2e/SoapUI/zaakbrug-e2e-soapui-project.xml:/project/zaakbrug-e2e-soapui-project.xml
      - ./e2e/Reports:/reports
    environment:
      - COMMAND_LINE=-s TestSuite -f/%reports% '/%project%/zaakbrug-e2e-soapui-project.xml' -a
    depends_on:
      zaakbrug:
        condition: service_healthy
    networks:
      - zaakbrug-stack
      - zaakbrug-backend

volumes:
  logs:
  media:
  private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
