version: '4'

services:
  open-zaak-redis:
    image: redis
    networks:
      - open-zaak-backend

  open-zaak-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/open-zaak-db/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - database-data:/var/lib/postgresql/data
    networks:
      - open-zaak-backend
    ports:
      - 5432

  open-zaak:
    image: openzaak/open-zaak:latest
    container_name: open-zaak
    environment: &open-zaak-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - OPENZAAK_DOMAIN=host.docker.internal:8000
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=openzaak
      - DB_USER=openzaak
      - DB_HOST=open-zaak-db
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=open-zaak-redis:6379/0
      - CACHE_AXES=open-zaak-redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@localhost
      - CELERY_BROKER_URL=redis://open-zaak-redis:6379/1
      - CELERY_RESULT_BACKEND=redis://open-zaak-redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      - SENDFILE_BACKEND=django_sendfile.backends.simple
      - NOTIFICATIONS_DISABLED=yes
    networks:
      - open-zaak
      - open-zaak-backend
    ports:
      - 8000:8000
    volumes: &open-zaak-volumes
      - media:/app/media
      - private-media:/app/private-media
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery:
    image: openzaak/open-zaak:latest
    environment: *open-zaak-env
    command: /celery_worker.sh
    volumes: *open-zaak-volumes
    networks:
      - open-zaak-backend
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery-flower:
    image: openzaak/open-zaak:latest
    environment: *open-zaak-env
    command: /celery_flower.sh
    networks:
      - open-zaak-backend
    ports:
      - 5555
    depends_on:
      - open-zaak-redis
      - open-zaak-celery

  open-zaak-nginx:
    image: nginx
    volumes:
      - ./docker/open-zaak-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - open-zaak
      - open-zaak-backend
    ports:
      - 9001:80
    depends_on:
      - open-zaak

  zaakbrug:
    environment:
      - zaakbrug.zgw.zaken-api.root-url=http://host.docker.internal:8000/zaken/api/v1/
      - zaakbrug.zgw.documenten-api.root-url=http://host.docker.internal:8000/documenten/api/v1/
      - zaakbrug.zgw.catalogi-api.root-url=http://host.docker.internal:8000/catalogi/api/v1/

volumes:
  database-data:
  media:
  private-media:

networks:
  open-zaak:
    name: zaakbrug-stack
  open-zaak-backend:

