version: "3"

services:
  frank:
    image: nexus.frankframework.org/frank-framework:latest
    volumes:
      - ./docker/context.xml:/usr/local/tomcat/conf/context.xml:ro
      - ./src/main/resources/:/opt/frank/resources/:ro
      - ./src/test/testtool/:/opt/frank/testtool/:ro
      - ./src/main/configurations/:/opt/frank/configurations/:ro
    ports:
      - "8080:8080"
    environment:
      - SET_PERMISSIONS_ON_STARTUP=FALSE
      - dtap.stage=LOC
      - instance.name=Frank2ZGW
      - database.instance.name=frank2zgw
      - database.host=database
      - database.name=database
      - database/username=database_user
      - database/password=database_password
    depends_on:
      - frankdatabase
  frankdatabase:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=database_password
      - POSTGRES_DB=database