# This is a compose file inteded for trying out the project locally and absolutely
# not suitable for production usage. The configuration here contains non-safe defaults.
#
# If you want to try out CMIS with Alfresco, see docker-compose.alfresco.yml
#
#       
#     command: postgres -c max_connections=300 -c log_min_messages=LOG -c log_statement=all
version: '4'

services:
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/postgresql/data
    ports:
      - "11234:5432"

  redis:
    image: redis

# Cannot rename this one because then container nginx produces an error
  web:
    image: openzaak/open-zaak:latest
    environment: &app-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=openzaak
      - DB_USER=openzaak
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@localhost
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
    ports:
      - 8000:8000
    volumes: &app-volumes
      - media:/app/media  # Shared media volume to get access to saved OAS files
      - private-media:/app/private-media
    depends_on:
      - db
      - redis

  celery:
    build: .
    image: openzaak/open-zaak:latest
    environment: *app-env
    command: /celery_worker.sh
    volumes: *app-volumes
    depends_on:
      - db
      - redis

  celery-flower:
    build: .
    image: openzaak/open-zaak:latest
    environment: *app-env
    command: /celery_flower.sh
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
    depends_on:
      - web

  zaakbrug:
    build: .
    image: zaak-brug:test
    container_name: zaak-brug
    environment:
      - dtap.stage=LOC
      - zgw.baseurl=http://web:8000/
      - JwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmcmFuayIsImlhdCI6MTY3NDQ5MjA4MywiY2xpZW50X2lkIjoiZnJhbmsiLCJ1c2VyX2lkIjoiIiwidXNlcl9yZXByZXNlbnRhdGlvbiI6IiJ9.RntFEAC5IetktZc-erfiLYhEvv3LxhCxl60kXQVqvVw
    ports:
      - 8080:8080
    depends_on:
      - nginx

volumes:
  db:
  media:
  private-media:
