version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  zaakbrug:
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-8.1.0-20240111.192324}
    image: wearefrank/zaakbrug:latest
    container_name: zaakbrug.dev
    environment:
      - zaakbrug.zds.timezone=UTC
      - TZ=Europe/Amsterdam
      - GC_LOGGING_ENABLED=false
      - "JAVA_OPTS=$JAVA_OPTS -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote \
                       -Dcom.sun.management.jmxremote.local.only=false \
                       -Dcom.sun.management.jmxremote.authenticate=false \
                       -Dcom.sun.management.jmxremote.port=9010 \
                       -Dcom.sun.management.jmxremote.rmi.port=9010 \
                       -Djava.rmi.server.hostname=0.0.0.0 \
                       -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      # - ./data:/usr/local/tomcat/data
      - ./src/main/configurations:/opt/frank/configurations:ro
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080
      - 9010:9010

volumes:
  logs:
  media:
  private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
