version: '4'

services:
  open-zaak-redis:
    image: redis

  open-zaak-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - database-data:/var/lib/postgresql/data
    ports:
      - "11234:5432"

  open-zaak:
    image: openzaak/open-zaak:latest
    container_name: open-zaak
    environment: &openzaak-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - OPENZAAK_DOMAIN=host.docker.internal:8000
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=openzaak
      - DB_USER=openzaak
      - DB_HOST=open-zaak-db
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=open-zaak-redis:6379/0
      - CACHE_AXES=open-zaak-redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@localhost
      - CELERY_BROKER_URL=redis://open-zaak-redis:6379/1
      - CELERY_RESULT_BACKEND=redis://open-zaak-redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      - SENDFILE_BACKEND=django_sendfile.backends.simple
      - NOTIFICATIONS_DISABLED=yes
    ports:
      - 8000:8000
    volumes: &openzaak-volumes
      - media:/app/media
      - private-media:/app/private-media
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery:
    image: openzaak/open-zaak:latest
    environment: *openzaak-env
    command: /celery_worker.sh
    volumes: *openzaak-volumes
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery-flower:
    image: openzaak/open-zaak:latest
    environment: *openzaak-env
    command: /celery_flower.sh
    ports:
      - 5555:5555
    depends_on:
      - open-zaak-redis
      - open-zaak-celery

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
    depends_on:
      - open-zaak

  zaakbrug:
    build: .
    image: wearefrank/zaakbrug:latest
    container_name: zaakbrug
    volumes: &zaakbrug-database-data
      - ../frank-runner/data:/usr/local/tomcat/data
      # - ./data:/usr/local/tomcat/data
    environment:
      - zgw.baseurl=http://host.docker.internal:8000/
    ports:
      - 8080:8080
    depends_on:
    - open-zaak

volumes:
  database-data:
  media:
  private-media:
