version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=zaakbrug
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zaakbrug:
    build: .
    image: wearefrank/zaakbrug:latest
    container_name: zaakbrug
    environment:
      - zaakbrug.zds.timezone=UTC
      - TZ=Europe/Amsterdam
    volumes: &zaakbrug-database-data
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      - ./docker/postgresql/context.xml:/usr/local/tomcat/conf/context.xml
      # - ./data:/usr/local/tomcat/data
    networks:
      - zaakbrug
      - zaakbrug-backend
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  logs:
  postgres:
  database-data:
  media:
  private-media:

networks:
  zaakbrug:
    name: zaakbrug-stack
  zaakbrug-backend:
