apiVersion: v1
kind: Service
metadata:
  name: {{ include "zaakbrug.fullname" . }}
  labels:
    {{- include "zaakbrug.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zaakbrug.selectorLabels" . | nindent 4 }}
---
{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zaakbrug.nginxFullname" . }}
  labels:
    {{- include "zaakbrug.nginxLabels" . | nindent 4 }}
  {{- with .Values.nginx.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }} : {{ tpl ($value | toString) $ }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "zaakbrug.nginxSelectorLabels" . | nindent 4 }}
{{- end -}}