apiVersion: v2
appVersion: 1.12.9
description: Install ZaakBrug (zds-to-zgw) on Haven, powerd by the Frank!Framework
name: zaakbrug
type: application
version: 0.7.8

home: https://github.com/ibissource/zaakbrug
icon: "https://raw.githubusercontent.com/ibissource/zaakbrug/master/zaakbrug-icon.png"

keywords:
  - zaak
  - zaaksysteem
  - brug
  - zds
  - zgw
  - esb
  - frank

dependencies:
  - name: openzaak
    version: "1.1.0"
    repository: "https://maykinmedia.github.io/charts/"
    condition: openzaak.staging.enabled
