apiVersion: v2
appVersion: 1.0
description: Install ZaakBrug (zds-to-zgw) on Haven, powerd by the Frank!Framework
name: zaakbrug
type: application
version: 0.2.0

home: https://github.com/ibissource/zaakbrug
icon: "https://raw.githubusercontent.com/ibissource/zaakbrug/master/favicon.svg"

keywords:
  - zaak
  - zaaksysteem
  - brug
  - zds
  - zgw
  - esb
  - frank