name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version-next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version-next: ${{ steps.reference.outputs.next-reference }}
      version-next-strict: ${{ steps.reference.outputs.next-reference }}
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #4.1.1

      - name: Next Reference
        id: reference
        uses: wearefrank/ci-cd-templates/next-reference@main

  ci:
    uses: wearefrank/ci-cd-templates/.github/workflows/ci-generic.yml@main
    needs:
      - version-next
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      version: ${{ needs.version-next.outputs.version-next }}
      docker-image-repo: ${{ vars.DOCKER_IMAGE_REPOSITORY }}
      docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
      upload-sarif-to-security: false
      run-frank-till-healthy-enabled: false

  run-soapui-tests:
    runs-on: ubuntu-latest
    needs:
      - version-next
      - ci
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #4.1.1

      - name: Download Docker tar
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe #4.1.2
        with:
          name: build-docker-image

      - name: Load Docker tar
        shell: bash
        run: |
          docker load --input image.tar
          docker image ls -a

      - name: Run SoapUI Tests
        run: |
          export ZAAKBRUG_VERSION="${{ needs.version-next.outputs.version-next }}"

          docker image inspect ${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_IMAGE_NAME }}:${ZAAKBRUG_VERSION}
          docker-compose -f ./docker-compose.zaakbrug.dev.yml -f ./docker-compose.zaakbrug.postgres.yml -f ./docker-compose.openzaak.dev.yml --profile soapui up -d
          docker ps

          sleep 90

          STATUS=$(docker inspect --format='{{json .State.Status}}' soapui-testrunner)
          until [ "$STATUS" = '"exited"' ]
          do
            STATUS=$(docker inspect --format='{{json .State.Status}}' soapui-testrunner)
            sleep 15
          done

          EXIT_CODE=$(docker inspect --format='{{json .State.ExitCode}}' soapui-testrunner)
          echo "Exit Code: $EXIT_CODE"

          docker-compose -f ./docker-compose.zaakbrug.dev.yml -f ./docker-compose.zaakbrug.postgres.yml -f ./docker-compose.openzaak.dev.yml down
          
          if [ "$EXIT_CODE" -ne 0 ]
            then
              echo "Test(s) failed. Failing the job."
              exit 1
          fi
        timeout-minutes: 15

      - name: Check if test reports created
        run: |
          if [ -z "$(ls -A e2e/reports)" ]
            then
              echo "There is no test report found, tests might not have been run. Failing the job."
              exit 1
          fi

      - name: Upload SoapUI testreports as artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 #4.3.1
        if: always()
        with:
          name: reports-soapui-testreports
          path: ./*/reports
