name: Update Helm Chart

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          repo: charts
          owner: wearefrank
          workflow: update-app-version.yml
          workflow_inputs: '{ "chart": "charts/zaakbrug", "appVersion": "1337" }'

      - name: Use the output run ID
        run: echo ${{steps.return_dispatch.outputs.run_id}}
